FACT-183: add Accept-Language header to api call
hmcts/fact-frontend pull request #98
Opened 2020-11-06 17:59 UTC by nigeldunne

### JIRA link ###

https://tools.hmcts.net/jira/browse/FACT-183

### Change description ###

Add welsh for api

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-11-08 12:37 UTC, linusnorton requested changes
please use a cookie to store language preference

2020-11-08 14:30 UTC, velimd commented on src/main/views/search/location.njk
> +      <form method="GET" action="/courts?lng=cy">
dont we get the language already from the request, dont think we need this.

2020-11-09 09:57 UTC, velimd approved these changes

2020-11-09 11:33 UTC, linusnorton approved these changes

2020-11-09 11:35 UTC, merged